Update the documentation at "README.md"
jenkins-infra/docs.jenkins.io pull request #135
Opened 2024-10-12 15:59 UTC by Brijeshthummar02

issue #121

2024-10-12 16:16 UTC, krisstern requested changes
My apologies @Brijeshthummar02, the README is actually and AsciiDoc, so you will need to revert to the syntax used previously.

2024-10-12 16:44 UTC, Brijeshthummar02 commented
can you specify the change i'm not geting it.
@krisstern

2024-10-12 16:46 UTC, krisstern commented
@Brijeshthummar02 Do you know the differences between an `.adoc` document and a `.md` document?

2024-10-12 16:48 UTC, Brijeshthummar02 commented
@krisstern i searched it, i'm working on it, submitting update soon.

2024-10-12 17:05 UTC, krisstern requested changes

2024-10-12 17:05 UTC, krisstern commented on README.adoc
> +- **Gatsby Documentation**: Non-versioned content managed via Gatsby. This forms the basis of the current [https://jenkins.io/](https://jenkins.io/) site, which will be replaced in the future. For mo
```suggestion
* **Gatsby Documentation**: Non-versioned content managed via Gatsby. This forms the basis of the current link:https://jenkins.io/[https://jenkins.io/] site, which will be replaced in the future. For more details on how to work with the Gatsby site, refer to its dedicated README documentation at: 
```

2024-10-12 17:05 UTC, krisstern commented on README.adoc
> +- **Antora Documentation**: This version-controlled documentation covers different guides (e.g., Developer Guide, User Guide).
```suggestion
* **Antora Documentation**: This version-controlled documentation covers different guides (e.g., Developer Guide, User Guide).
```

2024-10-12 17:05 UTC, krisstern commented on README.adoc
> +- Node.js official website: [https://nodejs.org](https://nodejs.org)
```suggestion
* Node.js official website: [https://nodejs.org](https://nodejs.org)
```

2024-10-12 17:05 UTC, krisstern commented on README.adoc
> +- NVM repository: [https://github.com/nvm-sh/nvm](https://github.com/nvm-sh/nvm)
```suggestion
* NVM repository: [https://github.com/nvm-sh/nvm](https://github.com/nvm-sh/nvm)
```

2024-10-12 17:05 UTC, krisstern commented on README.adoc
> +  [https://github.com/jenkins-infra/docs.jenkins.io/tree/main/site#readme](https://github.com/jenkins-infra/docs.jenkins.io/tree/main/site#readme)
```suggestion
** link:https://github.com/jenkins-infra/docs.jenkins.io/tree/main/site#readme/[https://github.com/jenkins-infra/docs.jenkins.io/tree/main/site#readme/]
```

2024-10-12 17:05 UTC, krisstern commented on README.adoc
> +If you have any contributions or updates for the documentation, feel free to submit a pull request.
```suggestion
If you have any queries or contributions or updates for the documentation, feel free to create an issue and/or submit a pull request.
```

2024-10-12 17:19 UTC, Brijeshthummar02 commented
@krisstern is latest commit fine?

2024-10-12 17:24 UTC, krisstern commented
Hi @Brijeshthummar02 I don't see any changes from you. You can simply commit my suggestions in a single batch by going to https://github.com/jenkins-infra/docs.jenkins.io/pull/135/files.

2024-10-13 11:18 UTC, krisstern requested changes

2024-10-13 11:18 UTC, krisstern commented on README.adoc
> +* link:http://127.0.0.1:8080/[http://127.0.0.1:8080]
```suggestion
* link:http://127.0.0.1:8080/[http://127.0.0.1:8080]

```

2024-10-13 11:18 UTC, krisstern commented on README.adoc
> +If you have any contributions or updates for the documentation, feel free to submit a pull request.
```suggestion

```

2024-10-13 11:19 UTC, krisstern requested changes

2024-10-13 11:19 UTC, krisstern commented on README.adoc
> +== Contributing
```suggestion
== Contributing

```

2024-10-13 14:47 UTC, Brijeshthummar02 commented
@krisstern  is it good to go now?

2024-10-15 23:30 UTC, krisstern requested changes

2024-10-15 23:30 UTC, krisstern commented on README.adoc
> +=== Building the Docs
```suggestion
=== Building the Versioned Docs
```

2024-10-15 23:30 UTC, krisstern commented on README.adoc
> +[source,bash]
```suggestion
[source,bash]
```

2024-10-15 23:30 UTC, krisstern commented on README.adoc
> +=== Prerequisites
```suggestion
=== Installing the Prerequisites
```

2024-10-15 23:30 UTC, krisstern commented on README.adoc
> +After installation, verify that both `node` and `npm` are correctly installed:
```suggestion
After the installation, verify that both `node` and `npm` are correctly installed:
```

2024-10-15 23:30 UTC, krisstern commented on README.adoc
> +npm install
```suggestion
npm i
```

2024-10-15 23:30 UTC, krisstern commented on README.adoc
> +npm install
It can be either `npm i` or `npm install`, I don't need this needs to be changed.

2024-10-15 23:30 UTC, krisstern commented on README.adoc
> +* link:http://127.0.0.1:8080/[http://127.0.0.1:8080]
```suggestion
* link:http://127.0.0.1:8080/[http://127.0.0.1:8080]

```

2024-10-17 15:45 UTC, krisstern requested changes
My bad, missed one

2024-10-17 15:45 UTC, krisstern commented on README.adoc
> +
```suggestion
+
```

2024-10-17 18:05 UTC, krisstern requested changes

2024-10-17 18:05 UTC, krisstern commented on README.adoc
> +
```suggestion
+
```

2024-10-17 18:05 UTC, krisstern commented on README.adoc
> +
It looks like you are removing too many of these `+` signs that are needed for continuity.

2024-10-18 05:22 UTC, Brijeshthummar02 commented
@krisstern i have gone through whole file by my own and added + wherever needed, also mention if more changes are required.

2024-10-18 05:41 UTC, krisstern requested changes

2024-10-18 05:41 UTC, krisstern commented on README.adoc
>  +
```suggestion

```

2024-10-18 05:50 UTC, krisstern approved these changes
Hi @Brijeshthummar02! LGTM, thanks for all the hard work

2024-10-18 05:53 UTC, Brijeshthummar02 commented
Hi @krisstern,

I just wanted to take a moment to thank you for all your support and guidance throughout this issue. Your patience and willingness to help have made a significant difference, and I truly appreciate it.

Best regards,
@Brijeshthummar02

2024-10-18 05:54 UTC, krisstern commented
Hey you are welcome @Brijeshthummar02! It has been a pleasure working with you 😃

2024-10-18 05:54 UTC, merged