fix gatsby build error due to the use of browser api's
jenkins-infra/docs.jenkins.io pull request #180
Opened 2024-11-26 07:31 UTC by KitsuneKode

Fixes #127

![image](https://github.com/user-attachments/assets/1e960a46-4e0b-4d59-b2db-c21952df27aa)

I added if checks so that code requiring browser apis are only executed on client side.
Build successful on my device.

I even tried to use polyfills such as  xmldom and jsdom, but it was not an optimal approach.

@krisstern  can you check this out and mention if something needs to be fixed?

2024-11-26 17:17 UTC, krisstern commented
Thanks @KitsuneKode for this PR! Let me review it over the next few days

2024-11-28 15:36 UTC, krisstern requested changes
Hi @KitsuneKode, thanks for the PR! There are some changes we will need to revert back to their previous state to make it work but this PR looks promising. 

Also, could you please add the following `script` to `site/package.json`?:
```json
"serve": "gatsby serve",
```
and also removing the redundant `start` script? 

Appreciate your help! We should be able to merge soon.

2024-11-28 16:02 UTC, KitsuneKode commented on site/src/components/RecentBlogPosts.js
> +                                                    src="../../static/images/images/avatars/no_image.svg"
I checked the development only, forgot to clean the cache

2024-11-28 16:03 UTC, krisstern requested changes

2024-11-28 16:03 UTC, krisstern commented on site/src/templates/author-pages.js
> +                                            : "../../images/avatars/no_image.svg"
```suggestion
                                            : "../../images/images/avatars/no_image.svg"
```

2024-11-28 16:03 UTC, KitsuneKode commented
@krisstern I think I made the changes, can you check if everything is in order or I missed something

2024-11-28 16:04 UTC, krisstern commented
You missed one @KitsuneKode

2024-11-28 16:12 UTC, KitsuneKode commented
I forgot to merge main on my end,

2024-11-28 16:29 UTC, krisstern approved these changes
Hi @KitsuneKode, thanks for all your hard work! The PR looks really good.

2024-11-28 16:30 UTC, merged

2024-11-28 16:30 UTC, KitsuneKode commented
Thank you @krisstern  happy to help