feat: Add dark mode in Gatsby site
jenkins-infra/docs.jenkins.io pull request #189
Opened 2024-11-30 18:52 UTC by saurabhraghuvanshii

Add dark mode in Gatsby site

Closes#185

![Screenshot 2024-12-01 002135](https://github.com/user-attachments/assets/af8f75ae-3bda-4733-b167-f3fe3bad9674)
![Screenshot 2024-12-01 002152](https://github.com/user-attachments/assets/6a2603f6-a1b0-4dcc-8582-699e3a863f0d)
![Screenshot 2024-12-01 002218](https://github.com/user-attachments/assets/03a65bfe-0b17-4292-bad1-f15ca9a6ec04)

2024-12-01 06:09 UTC, krisstern requested changes

2024-12-01 06:09 UTC, krisstern commented on site/src/css/authorpost.module.css
> +}
```suggestion
}

```

2024-12-01 06:09 UTC, krisstern commented on site/src/css/blogpost.module.css
> +}
```suggestion
}

```

2024-12-02 10:08 UTC, saurabhraghuvanshii commented
@krisstern sir , is any more changes required?

2024-12-07 11:51 UTC, krisstern approved these changes
Thanks @saurabhraghuvanshii for the PR! It looks good to me

2024-12-07 11:51 UTC, merged

2024-12-07 11:53 UTC, saurabhraghuvanshii commented
@krisstern welcome sir , sir I can make it responsive.