Update Makefile to clean and generate new UI bundle on `ui` rule
jenkins-infra/docs.jenkins.io pull request #43
Opened 2024-05-25 09:03 UTC by Vandit1604

The `ui` rule was not generating the new UI bundle on `make all`. I have updated the Makefile so it works properly.

2024-05-25 09:48 UTC, krisstern requested changes

2024-05-25 09:48 UTC, krisstern commented on Makefile
> +ui: clean
Are you using tab for the Makefile @Vandit1604? We are not supposed to use a single space here, so would like to double check with you

2024-05-25 09:48 UTC, krisstern commented on Makefile
> +antora: ui
Same here: use tabs, not spaces.

2024-06-02 14:18 UTC, krisstern approved these changes

2024-06-03 00:18 UTC, krisstern approved these changes

2024-06-03 00:19 UTC, krisstern commented
@kmartens27 Please approve this PR so I could merge it

2024-06-03 06:09 UTC, gounthar approved these changes

2024-06-03 06:09 UTC, merged